-- Sync employees.objective and employees.ai_group from Name Tags CSV.
-- Source: 2026 Retreat Planning & Spend - Name Tags (1).csv (2026-05-18 export)
-- Matches on first_name + last_name. Empty cells become NULL.

update employees as e
set objective = v.objective, ai_group = v.ai_group
from (values
  ('Aaron', 'Levin', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 16'),
  ('Ada', 'Vaughan', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 15'),
  ('Adam', 'Fachler', 'Objective 1 - Topic 1: Ramp Recruitment', 'Group 16'),
  ('Aditya', 'Vyas', 'Objective 3 - Topic 1: Performance', 'Group 10'),
  ('Alex', 'Voto', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 21'),
  ('Alex', 'Wu', 'Objective 1 - Topic 3: Application Velocity', 'Group 21'),
  ('Alex', 'Mootz', 'Objective 3 - Topic 1: Performance', 'Group 5'),
  ('Alexis', 'Grossman', 'Objective 2 - Topic: What does success look like?', 'Group 7'),
  ('Alexis', 'Downey', 'Objective 2 - Topic: What does success look like?', 'Group 2'),
  ('Amisha', 'Singla', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 14'),
  ('Amy Louise', 'Aasen', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 8'),
  ('Anke', 'Liu', 'Objective 1 - Topic 3: Application Velocity', 'Group 13'),
  ('Anup', 'Pani', 'Objective 3 - Topic 1: Performance', 'Group 21'),
  ('Aristides', 'Staffieri', 'Objective 3 - Topics 2: Faster and Safe', 'Group 10'),
  ('Aurora', 'Park-Guzman', 'Objective 2 - Topic: What does success look like?', 'Group 22'),
  ('Becks', 'Palia', 'Objective 2 - Topic: What does success look like?', 'Group 18'),
  ('Betty', 'Sun-Lucas', 'Objective 2 - Topic: What does success look like?', 'Group 16'),
  ('Bianca', 'Hearfield', 'Objective 2 - Topic: What does success look like?', 'Group 7'),
  ('BJ', 'Mahal', 'Objective 1 - Topic 1: Ramp Recruitment', 'Group 20'),
  ('Branden', 'Hui', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 6'),
  ('Brett', 'Boston', 'Objective 3 - Topic 1: Performance', 'Group 14'),
  ('Bri', 'Wylde', 'Objective 1 - Topic 3: Application Velocity', 'Group 17'),
  ('Bruno', 'Muller', 'Objective 1 - Topic 3: Application Velocity', 'Group 5'),
  ('Candace', 'Kelly', 'Objective 1 - Topic 1: Ramp Recruitment', 'Group 18'),
  ('Cassio', 'Goulart', 'Objective 3 - Topics 2: Faster and Safe', 'Group 20'),
  ('Cem', 'Arcan', NULL, 'Group 24'),
  ('Chenhao', 'Li', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 2'),
  ('Chris', 'Frost', 'Objective 3 - Topic 1: Performance', 'Group 21'),
  ('Christal', 'Gauthier', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 9'),
  ('Christian', 'Jonas', 'Objective 3 - Topic 1: Performance', 'Group 14'),
  ('Christin', 'Spradley', 'Objective 2 - Topic: What does success look like?', 'Group 11'),
  ('Claire', 'Grant', 'Objective 1 - Topic 1: Ramp Recruitment', 'Group 12'),
  ('Claudia', 'Novo De Azevedo Antunes', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 23'),
  ('Dan', 'Konar', 'Objective 2 - Topic: What does success look like?', 'Group 7'),
  ('Daniel', 'Casanas', 'Objective 1 - Topic 1: Ramp Recruitment', 'Group 19'),
  ('Daniel', 'Rebelsky', 'Objective 3 - Topics 2: Faster and Safe', 'Group 20'),
  ('Daniel', 'Giffin', NULL, 'Group 25'),
  ('Danielle', 'Nelson', 'Objective 2 - Topic: What does success look like?', 'Group 17'),
  ('Darpan', 'Vedi', 'Objective 3 - Topics 2: Faster and Safe', 'Group 3'),
  ('David', 'Mazieres', NULL, 'Group 14'),
  ('De-Ann', 'Abraham', 'Objective 1 - Topic 3: Application Velocity', 'Group 1'),
  ('Denelle', 'Dixon', NULL, 'Group 24'),
  ('Derek', 'Chen', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 19'),
  ('Destinee', 'Agard', NULL, NULL),
  ('Dominic', 'Althoff', 'Objective 2 - Topic: What does success look like?', 'Group 4'),
  ('Elizabeth', 'Morris', 'Objective 2 - Topic: What does success look like?', 'Group 18'),
  ('Ellen', 'Canale', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 2'),
  ('Elliot', 'Voris', 'Objective 1 - Topic 1: Ramp Recruitment', 'Group 21'),
  ('Emir', 'Ayral', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 19'),
  ('Eric', 'Wingrove', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 18'),
  ('Federico', 'Gomez Schumacher', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 23'),
  ('Flint', 'Soriano', NULL, NULL),
  ('Gaby', 'Pellagatti', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 1'),
  ('Garand', 'Tyson', 'Objective 3 - Topic 1: Performance', 'Group 5'),
  ('Gemma', 'Dobbs', 'Objective 1 - Topic 3: Application Velocity', 'Group 13'),
  ('Geoff', 'Ramseyer', NULL, 'Group 4'),
  ('George', 'Kudrayvtsev', 'Objective 3 - Topics 2: Faster and Safe', 'Group 25'),
  ('Giuliano', 'Losa', 'Objective 2 - Topic: What does success look like?', 'Group 13'),
  ('Hunter', 'Pack', 'Objective 1 - Topic 3: Application Velocity', 'Group 17'),
  ('Iftach', 'Haitner', 'Objective 3 - Topic 1: Performance', 'Group 5'),
  ('Iveta', 'Lacane', 'Objective 3 - Topics 2: Faster and Safe', 'Group 13'),
  ('Jacek', 'Nykis', 'Objective 3 - Topics 2: Faster and Safe', 'Group 6'),
  ('Jack', 'Humphries', 'Objective 3 - Topic 1: Performance', 'Group 4'),
  ('Jacob', 'Urban', 'Objective 1 - Topic 1: Ramp Recruitment', 'Group 3'),
  ('Jamie', 'Bonnifield', 'Objective 2 - Topic: What does success look like?', 'Group 16'),
  ('Jane', 'Wang', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 1'),
  ('Jason', 'Karsh', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 18'),
  ('Jason', 'Espino', NULL, 'Group 24'),
  ('Jay', 'Geng', 'Objective 3 - Topic 1: Performance', 'Group 16'),
  ('Jeesun', 'Kim', 'Objective 3 - Topic 1: Performance', 'Group 15'),
  ('Jerry', 'Xu', 'Objective 2 - Topic: What does success look like?', 'Group 12'),
  ('Jiahui', 'Hu', 'Objective 3 - Topics 2: Faster and Safe', 'Group 14'),
  ('Jose', 'Fernandez da Ponte', NULL, 'Group 20'),
  ('Juan', 'López Carretero', 'Objective 1 - Topic 1: Ramp Recruitment', 'Group 23'),
  ('Justin', 'Shaw', 'Objective 1 - Topic 1: Ramp Recruitment', 'Group 8'),
  ('Justin', 'Rice', 'Objective 1 - Topic 3: Application Velocity', 'Group 6'),
  ('Kanwalpreet', 'Dhindsa', 'Objective 3 - Topics 2: Faster and Safe', 'Group 6'),
  ('Karthik', 'Iyer', 'Objective 3 - Topic 1: Performance', 'Group 10'),
  ('Kate', 'Montgomery', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 9'),
  ('Katherine', 'Creeden', 'Objective 2 - Topic: What does success look like?', 'Group 12'),
  ('Kathy', 'Sindac', 'Objective 2 - Topic: What does success look like?', 'Group 12'),
  ('Kelly', 'Hendricks', 'Objective 2 - Topic: What does success look like?', 'Group 23'),
  ('Kevin', 'Becker-Torres', 'Objective 2 - Topic: What does success look like?', 'Group 22'),
  ('Klint', 'Koether', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 19'),
  ('Kofi', 'Baryeh Jr.', 'Objective 2 - Topic: What does success look like?', 'Group 3'),
  ('Kyle', 'Fahey', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 23'),
  ('Lauren', 'Strasburg', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 10'),
  ('Leigh', 'McCulloch', 'Objective 3 - Topic 1: Performance', NULL),
  ('Lisa', 'Macnew', 'Objective 2 - Topic: What does success look like?', 'Group 11'),
  ('Liz', 'Ray', 'Objective 2 - Topic: What does success look like?', 'Group 19'),
  ('Magdiela', 'Rivas Nunez', 'Objective 1 - Topic 1: Ramp Recruitment', 'Group 2'),
  ('Malte', 'Baumann', 'Objective 2 - Topic: What does success look like?', 'Group 16'),
  ('Marcelo', 'Salloum dos Santos', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 3'),
  ('Marcelo', 'Prates', 'Objective 2 - Topic: What does success look like?', 'Group 8'),
  ('Mark', 'Harris', 'Objective 2 - Topic: What does success look like?', 'Group 4'),
  ('Mark', 'Mayo', NULL, 'Group 24'),
  ('Marlon', 'Dulay', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 25'),
  ('Marta', 'Lokhava', 'Objective 3 - Topic 1: Performance', 'Group 5'),
  ('Marwen', 'Abid', 'Objective 1 - Topic 1: Ramp Recruitment', 'Group 5'),
  ('Meghan', 'Rosenberg', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 22'),
  ('Mel', 'Higgins', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 9'),
  ('Michael', 'Berryhill', 'Objective 3 - Topic 1: Performance', 'Group 8'),
  ('Michaela', 'Sullivan Shuck', 'Objective 2 - Topic: What does success look like?', 'Group 9'),
  ('Minkyeong', 'Shin', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 15'),
  ('Nadine', 'Chakar', NULL, NULL),
  ('Nastascia', 'Phillips', 'Objective 2 - Topic: What does success look like?', 'Group 17'),
  ('Natalia', 'Rocco', 'Objective 3 - Topic 1: Performance', 'Group 22'),
  ('Nicholas', 'Gilbert', 'Objective 3 - Topic 1: Performance', 'Group 6'),
  ('Nicolas', 'Barry', NULL, 'Group 8'),
  ('Nicole', 'Adair', 'Objective 1 - Topic 1: Ramp Recruitment', 'Group 15'),
  ('Niroja', 'Panda', 'Objective 2 - Topic: What does success look like?', 'Group 9'),
  ('Omar', 'Hamwi', 'Objective 1 - Topic 3: Application Velocity', 'Group 2'),
  ('Pat', 'Burgwinkle', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 7'),
  ('Paul', 'Wong', 'Objective 1 - Topic 1: Ramp Recruitment', 'Group 7'),
  ('Petar', 'Maymounkov', NULL, 'Group 25'),
  ('Piyal', 'Basu', 'Objective 3 - Topics 2: Faster and Safe', 'Group 14'),
  ('Pooja', 'Doctor', 'Objective 1 - Topic 1: Ramp Recruitment', 'Group 15'),
  ('Priscilla', 'Ma', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 1'),
  ('Punia', 'Punia', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 1'),
  ('Rachael', 'Rodriguez', 'Objective 2 - Topic: What does success look like?', 'Group 7'),
  ('Raja', 'Chakravorti', NULL, 'Group 11'),
  ('Ricky', 'Lindenhovius', 'Objective 3 - Topics 2: Faster and Safe', 'Group 6'),
  ('Riley', 'Hayes', 'Objective 2 - Topic: What does success look like?', 'Group 8'),
  ('Rob', 'Durscki', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 11'),
  ('Ronnie', 'Gabinay', 'Objective 2 - Topic: What does success look like?', 'Group 17'),
  ('Ryan', 'Stutsman', 'Objective 3 - Topic 1: Performance', 'Group 21'),
  ('Ryan', 'Yang', 'Objective 3 - Topics 2: Faster and Safe', 'Group 14'),
  ('Sagar', 'Patil', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 20'),
  ('Sahar', 'Bayat', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 12'),
  ('Saka', 'Nuru', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 9'),
  ('Sam', 'Eyob', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 19'),
  ('Sara', 'Arguello-Johansen', 'Objective 2 - Topic: What does success look like?', 'Group 25'),
  ('Sarah', 'Smyth', 'Objective 1 - Topic 1: Ramp Recruitment', 'Group 11'),
  ('Scott', 'Nystrom', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 4'),
  ('Seth', 'Tator', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 24'),
  ('Shama', 'Arakeri', 'Objective 2 - Topic: What does success look like?', 'Group 13'),
  ('Shaun', 'Johnson', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 23'),
  ('Shyam', 'Patel', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 1'),
  ('Siddharth', 'Suresh', 'Objective 3 - Topics 2: Faster and Safe', 'Group 10'),
  ('Sloane', 'Buckley', 'Objective 3 - Topics 2: Faster and Safe', 'Group 22'),
  ('Steph', 'Orpilla', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 15'),
  ('Steve', 'Harelick', NULL, NULL),
  ('Syd', 'Wiseman', 'Objective 3 - Topic 1: Performance', 'Group 22'),
  ('Sydney', 'Cavanagh', 'Objective 3 - Topic 1: Performance', 'Group 25'),
  ('Taha', 'Aziz', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 10'),
  ('Teague', 'Kaylor', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 13'),
  ('Tom', 'Levett', 'Objective 1 - Topic 1: Ramp Recruitment', 'Group 2'),
  ('Tomer', 'Weller', 'Objective 3 - Topic 1: Performance', 'Group 3'),
  ('Tony', 'Ye', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 3'),
  ('Tracey', 'Robinson', 'Objective 2 - Topic: What does success look like?', 'Group 17'),
  ('Traver', 'Tischio', 'Objective 3 - Topic 1: Performance', 'Group 3'),
  ('Trevor', 'Thayer', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 20'),
  ('Trong', 'Nguyen', 'Objective 2 - Topic: What does success look like?', 'Group 18'),
  ('Tyler', 'van der Hoeven', 'Objective 1 - Topic 3: Application Velocity', 'Group 4'),
  ('Vinita', 'Pawar', NULL, NULL),
  ('Vivian', 'Bui', NULL, NULL),
  ('Wela', 'Quan', 'Objective 2 - Topic: What does success look like?', 'Group 11'),
  ('Wen', 'Zhao', 'Objective 1 - Topic 2: RWA & DeFi', 'Group 12'),
  ('Will', 'Palmeri', NULL, 'Group 24')
) as v(first_name, last_name, objective, ai_group)
where e.first_name = v.first_name and e.last_name = v.last_name;
